# Generated by Django 4.2.3 on 2024-01-03 16:33

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[accounts.validators.validate_avatar_type, accounts.validators.validate_avatar_dimensions]),
        ),
    ]
