# Generated by Django 4.2.3 on 2024-03-15 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to=models.Q(
                    ("is_author", True), ("is_superuser", True), _connector="OR"
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="review_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
