# Generated by Django 4.2.3 on 2024-05-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_category_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
