# Generated by Django 4.2.3 on 2024-05-17 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
        ("blog", "0004_delete_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="publication",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comments.publication",
            ),
        ),
    ]
