# Generated by Django 4.2.3 on 2023-09-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='unlogged_user',
            field=models.CharField(blank=True, default='guest', max_length=50, null=True),
        ),
    ]
