# Generated by Django 4.2.3 on 2023-07-10 14:27

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/', validators=[reviews.validators.validate_avatar_type, reviews.validators.validate_avatar_dimensions, reviews.validators.validate_avatar_size]),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
