# Generated by Django 4.2.3 on 2023-07-25 09:53

from django.db import migrations
import django_resized.forms
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, None], upload_to='review_images/', validators=[reviews.validators.validate_avatar_type]),
        ),
    ]
