# Generated by Django 4.2.3 on 2023-09-08 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unlogged_user",
                    models.CharField(
                        blank=True, default="Guest", max_length=50, null=True
                    ),
                ),
                (
                    "pub_datetime",
                    models.DateTimeField(verbose_name=django.utils.timezone.now),
                ),
                ("body", models.TextField()),
                ("active", models.BooleanField(default=False)),
                (
                    "logged_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reviews.post"
                    ),
                ),
            ],
        ),
    ]
