# Generated by Django 4.2.3 on 2023-08-17 06:38

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('reviews', '0002_alter_post_image_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags (case-insensitive).', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
