# Generated by Django 4.2.3 on 2023-07-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[('DRAFT', 'Draft'), ('TO_PUB', 'Prepared to publish'), ('PUB', 'Published')], default=0),
        ),
    ]
