# Generated by Django 4.2.3 on 2023-11-20 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='response_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.comment'),
        ),
    ]
