# Generated by Django 4.2.3 on 2023-11-21 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_comment_response_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_top_level',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='response_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.comment'),
        ),
    ]
