# Generated by Django 4.2.3 on 2023-11-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_comment_is_top_level_alter_comment_response_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_top_level',
            new_name='top_level',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.post'),
        ),
    ]
