# Generated by Django 4.2.3 on 2023-07-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('TO_PUB', 'Prepared to publish'), ('PUB', 'Published')], default='DRAFT', max_length=50),
        ),
    ]
