# Generated by Django 4.2.3 on 2023-11-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_rename_is_top_level_comment_top_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='top_level',
        ),
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
