# Generated by Django 4.2.3 on 2023-11-21 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_remove_comment_top_level_comment_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='level',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
    ]
