# Generated by Django 4.2.3 on 2024-03-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="static/images/default_product_image.png",
                upload_to="product_images/",
            ),
        ),
    ]
