# Generated by Django 4.2.3 on 2024-05-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
        ("shop", "0006_brand_alter_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comments.publication",
            ),
        ),
    ]
